### ISSUE TITLE
Stm32f105 support?

### ISSUE THREAD

**Issue by penfold42** [keirf/FF_OSD#10]
How tricky is it to include building for the 105 ?

I’m looking at the hardware designs and adding USB OTG for a keyboard to Amiga adaptor would cost virtually zero.

If it’s not too painful we should reserve A11 and A12

**Comment by keirf** [comment]
There's basically no difference bringing up a 103 and a 105. I think you would find the existing firmware build just works!

**Comment by penfold42** [comment]
Excellent, thanks.

Btw, FF is my first time using STM32 so apologies in advance if I ask a few “dumb” questions

**Comment by penfold42** [comment]
You’re correct - flashed the OSD.bin to a gotek whilst troubleshooting a hardware fault - and serial output certainly works
