### ISSUE TITLE
Hot keys should be edge triggered

### ISSUE THREAD

**Issue by penfold42** [keirf/FF_OSD#12]
I haven’t put the scope on it yet but holding multiple keys looks like it’s doing PWM on the outputs

**Comment by keirf** [comment]
Oh I meant to fix that. But all the same given the BSRR write should match the existing pins settings, I'm surprised the output pins oscillate?

**Comment by keirf** [comment]
I can't repro unstable output pins, is that due to other changes in your tree?

**Comment by keirf** [comment]
Oh hang on I see what you mean: Multiple hot keys simultaneously? Why would you do that...

**Comment by penfold42** [comment]
Never underestimate the stupidity, or creativity, of explorative testers

**Comment by keirf** [comment]
Haha, now fixed anyway :) Maybe not worth a new release in itself, as requires user to build the firmware themselves anyway, to see the problem.

My current minor annoyance is my first display of the OSD box is glitching again. That means the first time after power on, or OSD reset, that the OSD box appears (eg. Ctrl-Alt-Return) I see an instantaneous screen glitch. It does not happen again until next full reinitialisation. Can you repro that? It's very weird and I have no idea why it happens!
