### ISSUE TITLE
clarification request for OSD instructions

### ISSUE THREAD

**Issue by kipper2k** [keirf/FF_OSD#13]
Hi,

 I am not sure where these connections are on a gotek in order to enable osd and OLED...
"OSD alongside LCD/OLED: (FlashFloppy v3.4a and later only) Place a jumper across pins A0-A1."

 where is A0 - A1 on the Gotek ?

thanks

Brian

**Comment by penfold42** [comment]
It’s on the OSD board, not the gotek

**Comment by keirf** [comment]
Yes FF OSD uses another stm32 chip. Currently 103c8t6 but it could probably run on almost any f1. Or be ported to another stm32 model range if economics support it (chip cost)
