### ISSUE TITLE
User pin limitation

### ISSUE THREAD

**Issue by BwanaFr** [keirf/FF_OSD#30]
Dear Keir,

One simple question about user pins.
In the firmware code, you mentioned pin B8-B10 for user pins.
I don't see any limitations to use pin B11-B13 too.

I'm I right?

Many thanks!

**Comment by keirf** [comment]
You could definitely use them, I may allocate them to other purposes in future though!

**Comment by BwanaFr** [comment]
Perfect!
I need one more pin!

**Comment by BwanaFr** [comment]
Thanks Keir!
