### ISSUE TITLE
Inverted Mode using OSD

### ISSUE THREAD

**Issue by jgilcas** [keirf/FF_OSD#36]
I have installed a BP in a spectrum and the result has been great, but there is a detail that I do not understand, everyone appears the letters in color and to me appears the background color and transparent letters, I have reviewed configuration but can not find anything. What can be? I did not have 4k7 and I put 10k, to pull up would work the same, right?
![image_2021-01-05_09-53-31](https://user-images.githubusercontent.com/37148968/103626532-9caabf80-4f3c-11eb-8da1-0157fcc2a494.png)

**Comment by keirf** [comment]
Have you attached to the green signal only in the Spectrum? Perhaps you are overdriving the signal, in which case you should try connecting with a bigger series resistor to the green signal.

**Comment by jgilcas** [comment]
Maybe i´m wrong and my picture is ok. Let me attach two pictures.

Non Inverted?
![noninverted](https://user-images.githubusercontent.com/37148968/103635421-c964d400-4f48-11eb-9628-7c4794af19b4.JPG)

Inverted?
![inverted](https://user-images.githubusercontent.com/37148968/103635423-c9fd6a80-4f48-11eb-987c-796d87886c0e.JPG)

**Comment by keirf** [comment]
Sorry yes, I think all the above are correct including your original picture. Assuming you are on the green signal, lettering will be adding green and the OSD box background is subtracting green.

On the Spectrum, the white background is already "full green". You can't add more green. Hence the lettering appears like the main background (white), while the OSD background is predominantly red+blue (=purple).

On the Kickstart screen, the white background is a dull white and the analog green can be overdriven to give a pale green. Again the OSD box is predominantly red+blue=purple, but it just happens to be paler here.

And the Amiga Test Kit screen is predominantly dark red, not much blue or green. So the OSD text stands out as vivid red and the OSD box, having little of any RGB, is almost black.

So, that's just how it is :)

**Comment by penfold42** [comment]
The only way to make it “better” is to use an analog switch and completely replace the original video signals.
There’s a display enable signal that can be used to drive this but it’s a much more complicated install as you need to more electronics and you need to cut traces on the computer.

**Comment by jgilcas** [comment]
No no, this solutions is perfect for me, my mistake was not try with
another backgrounds, now i tested with black background and it's perfect,
awesome.
