### ISSUE TITLE
Cannot enter 'Configure FF OSD' from main menu

### ISSUE THREAD

**Issue by snhirsch** [keirf/FF_OSD#37]
Title says it.  With no USB stock inserted I can enter the main menu by pushing both buttons, then scroll to the OSD setup option by moving left or right.  However, when at the OSD setup prompt nothing I do will convince it to enter that submenu.  What am I missing?  Currently using firmware 3.22.

**Comment by keirf** [comment]
Not using OSD extended protocol? Have you jumpered A0-A1 on the blue pill?

**Comment by snhirsch** [comment]
Oh, bother...  My mistake!  I didn't pay attention to what I was reading and somehow thought it was configuration for the OLED display.  Sincerest apologies for the high specific gravity here.
