### ISSUE TITLE
Cant get a synced video signal on a Amiga 500 Rev 8A

### ISSUE THREAD

**Issue by ninjafahrer** [keirf/FF_OSD#39]
FF OSD is correctly wired and a OLED Display is connected in parallel.
I am using Firmware 1.8 together with FF Geotk 3.16A.
I am getting no sync with the video Signal, have a lot of green lines on the screen.
The Amiga is connected via Scart to a TV with a PAL signal.
Removing the OLED has no effect.

FF OSD settings are on Auto.

**Comment by keirf** [comment]
Do you have a picture of the effect? Do you have a ground connection to the Amiga board (via I2C ground wire via Gotek will do, so probably this is ok)? Do you have a picture of your connections to the Amiga mainboard?

**Comment by ninjafahrer** [comment]
[
![IMG_20210224_203944](https://user-images.githubusercontent.com/79564439/109056348-99cc7f80-76e0-11eb-87b6-a02ce6a5f5ec.jpg)
![IMG_20210224_203807](https://user-images.githubusercontent.com/79564439/109056373-a18c2400-76e0-11eb-92f9-195c70794b5a.jpg)
![IMG_20210224_203713](https://user-images.githubusercontent.com/79564439/109056384-a81a9b80-76e0-11eb-9cba-8c07403c872c.jpg)

**Comment by keirf** [comment]
Where exactly do you pick up _CSYNC signal? It's hard to tell where that second wire goes, which appears to terminate directly below the ODD CIA lettering. But I'm pretty sure there's no _CSYNC in that little area.

**Comment by ninjafahrer** [comment]
![16143223228042112436215](https://user-images.githubusercontent.com/79564439/109265940-9bdd2e00-7807-11eb-87dc-181f02c33016.jpg)

**Comment by penfold42** [comment]
I think thats the wrong pin for CSYNC
try this:
![image](https://user-images.githubusercontent.com/13173376/109268357-108f8700-785f-11eb-954a-aaa2ec3d8b5f.png)

https://www.amigapcb.org/ is a BRILLIANT site

**Comment by keirf** [comment]
As @penfold42 says.

**Comment by ninjafahrer** [comment]
Great, that solved the problem!

Thanks for your support!

**Comment by penfold42** [comment]
Excellent !
