### ISSUE TITLE
Control the size of OSD or file name only via setting in FlashROM

### ISSUE THREAD

**Issue by Wierzbowsky** [keirf/FF_OSD#49]
Currently, when the A0-A1 jumper is set, the OSD shows enlarged file name with a slash on top of the window:
![image](https://user-images.githubusercontent.com/16538424/188437510-3bd73099-a07b-4849-acba-77559d9e4c02.png)

This is not controlled by any setting stored in the FlashROM. The only way to disable this is to remove the jumper. But then the enhanced protocol stops working and it's no longer possible to configure FF OSD settings using Gotek's pushbuttons.

I propose to disable enlarging the disk's name using the jumper and instead enhance the options of the "Display Height" setting. There could be the following options: "Normal", "Double size" and "Enlarged disk name". Then people could keep the A0-A1 jumper and configure the OSD with Gotek's buttons without having the forcefully enlarged OSD frame. Much better than to connect UART all the time when there's a need to change something.

**Comment by keirf** [comment]
The OSD size and layout is controlled by the Gotek (ie FlashFloppy). Here is a new FlashFloppy build for you to try. The download link requires you to be logged in to GitHub.

https://github.com/keirf/flashfloppy/suites/8138454716/artifacts/352836458

With this firmware version, try the following line in FF.CFG:
```
osd-display-order=0,1
```

**Comment by Wierzbowsky** [comment]
Thanks! I tested this version today. The slash in the upper left corner is gone, but the line it was at is still there, so there's the same extra one-line gap on top of the OSD as before. 

By default, with A0-A1 jumper and no USB flash, the OSD comes with the enlarged DSK image name (this is expected):
![image](https://user-images.githubusercontent.com/16538424/188954690-ba78191a-4d6e-43d4-8def-abc29c4e9afc.png)

With the FF.CFG with the proposed "osd-display-order" setting, the OSD is vertically normal (groovy!), but still enlarged horizontally (not expected):
![image](https://user-images.githubusercontent.com/16538424/188954905-29e1769f-ac1b-4a8d-ad4e-294f9169b08c.png)

Would it be possible to fix the horizontal size too? Thanks in advance.

**Comment by keirf** [comment]
I'll have a think about the horizontal size. Apart from that it's as expected. Banner text layout doesn't have configurable layout.

**Comment by keirf** [comment]
The wide box can fit long filenames though. But you'd rather scroll?

**Comment by Wierzbowsky** [comment]
> The wide box can fit long filenames though. But you'd rather scroll?

Yes, I'd rather have a compact OSD. The biggest benefit of the compact OSD is that you can put it in any corner of the screen.

**Comment by Wierzbowsky** [comment]
@keirf Keir, may I hope for the version with the normal size of the OSD frame? Thanks.

**Comment by keirf** [comment]
Do you want a special build? That's easy. Working out how to make it configurable would need more thought.

**Comment by Wierzbowsky** [comment]
No, I'd better wait for the generic solution. However, if you disable the default enlargement of OSD (both horizontal and vertical) in the master branch of FF firmware when the special protocol is used, that would be already sufficient. And maybe later it could be made configurable, but there's no rush. Thanks.

**Comment by keirf** [comment]
Yes, but I'm not intending to change the default.

**Comment by Wierzbowsky** [comment]
Then making it configurable via FF.CFG would be best. I will wait for the solution. 

With the screenless Gotek and the Blue Pill, it's essential to have the enhanced protocol enabled in order to configure the settings via Gotek's buttons. At the same time, the large size of the OSD makes it unmovable to other parts of the screen. As the upper left corner of the MSX screen is usually quite "busy", moving the OSD to either of the right corners would be the best idea, but with the enlarged OSD this is simply impossible - it occupies too large part of the MSX screen (which is 265x212). I hope that you understand the problem that we have here.

**Comment by keirf** [comment]
Yes, I see...

**Comment by Wierzbowsky** [comment]
I've made the board to connect the Blue Pill to all 3 color channels. The size is 32mm X 30mm. Thanks to @keirf for the idea.

![photo_2022-09-23_21-51-37](https://user-images.githubusercontent.com/16538424/192104838-3127c091-5887-47e6-b87f-4e382167702a.jpg)

**Comment by keirf** [comment]
Here is a new build for you to try, with a new config option. Try `osd-columns = 16`

You will need to be logged into GitHub for this download link to work:
https://github.com/keirf/flashfloppy/suites/8685546132/artifacts/391637682

**Comment by Wierzbowsky** [comment]
Many thanks! Works as desired now with the following settings:

osd-display-order = 0,1
osd-columns = 16
display-off-secs = 5

Will you include this feature into one of the upcoming 3.xx releases? I will need to write an article with modding instructions and recommended settings in the FF.CFG file and then share it with the MSX community.

**Comment by keirf** [comment]
I am fixing SD card support on 435 chip. Then I will do a release. Maybe in about a week.

**Comment by Wierzbowsky** [comment]
Confirmed to be working with v3.36! Many thanks!

The project is complete:
https://www.msx.org/forum/msx-talk/hardware/flashfloppy-osd-is-now-available-on-msx#comment-434835
