### ISSUE TITLE
A600 video info

### ISSUE THREAD

**Issue by penfold42** [keirf/FF_OSD#5]
If you are only using RGB analog (and not composite) the same approach as the A1200 should work.
E253R	CSYNC
E260R	Red
E259R	Green
E258R	Blue

If you also want the OSD to work via composite (or S-Video if you have modified it) then we will need to test a slightly different approach. If will likely involve injecting the video into R212 or R215:
![image](https://user-images.githubusercontent.com/13173376/65395948-75ca8780-dde4-11e9-81a0-d8024f2b4372.png)

**Comment by keirf** [comment]
I will add info on this to the wiki. Looks like no handy test point for kbd signals either, sadly.

**Comment by keirf** [comment]
I have updated the wiki, please take a look. I'm pretty sure mixing OSD into the signal at R211-213 will work fine. Perhaps the 150-ohm impedance will require a slightly bigger-than-usual resistor in the OSD wire.

**Comment by penfold42** [comment]
Looks good - I may soon have access to a 600 for validation

**Comment by keirf** [comment]
It would be nice to get photos too... Perhaps we leave this open for a bit.

**Comment by penfold42** [comment]
Of course !
